# Generated by Django 4.2.7 on 2023-11-08 15:07

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=sorl.thumbnail.fields.ImageField(upload_to="profiles"),
        ),
    ]
