# Generated by Django 4.2.7 on 2023-12-11 21:01

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                default="profiles/IMG_3450.jpg", upload_to="profiles"
            ),
        ),
    ]
