# Generated by Django 4.2.7 on 2023-12-11 21:12

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="banner_image",
            field=sorl.thumbnail.fields.ImageField(
                default="profies/default_user.jpg", upload_to="profiles"
            ),
        ),
    ]
