# Generated by Django 4.2.7 on 2023-12-11 21:18

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_profile_banner_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="banner_image",
            field=sorl.thumbnail.fields.ImageField(
                default="profiles/default_user.jpg", upload_to="profiles"
            ),
        ),
    ]
